name: mapmyindia_flutter
description: Unoffical MapMyIndia Flutter packages.
version: 0.0.1
homepage: https://github.com/nikhiladmin/mapmyindia-flutter.git

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  http: ^0.12.2

dev_dependencies:
