name: mapmyindia_flutter
description: A new Flutter package project.
version: 0.0.1
author: Nikhil Kumar Singh <nikhilbcps@gmail.com>
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  http: ^0.12.2

dev_dependencies:
